include_directories(/git/poco/Foundation/include)
include_directories(/git/poco/Zip/include)
include_directories(/git/poco/Crypto/include)
include_directories(/git/poco/Net/include)
include_directories(/git/poco/Util/include)
