include_directories(/home/master/3rdParty/poco/Foundation/include)
include_directories(/home/master/3rdParty/poco/Zip/include)
include_directories(/home/master/3rdParty/poco/Crypto/include)
include_directories(/home/master/3rdParty/poco/Net/include)
include_directories(/home/master/3rdParty/poco/Util/include)
