/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * Backup.h
 *
 * 
 */

#ifndef Backup_H_
#define Backup_H_


#include "ModelBase.h"

#include <string>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Backup
    : public ModelBase
{
public:
    Backup();
    virtual ~Backup();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Backup members

    /// <summary>
    /// 
    /// </summary>
    int64_t getId() const;
    void setId(int64_t value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// 
    /// </summary>
    int64_t getBackupDefId() const;
    void setBackupDefId(int64_t value);
    bool backupDefIdIsSet() const;
    void unsetBackupDefId();
    /// <summary>
    /// 
    /// </summary>
    std::string getStatus() const;
    void setStatus(std::string value);
    bool statusIsSet() const;
    void unsetStatus();
    /// <summary>
    /// 
    /// </summary>
    std::string getStarted() const;
    void setStarted(std::string value);
    bool startedIsSet() const;
    void unsetStarted();
    /// <summary>
    /// 
    /// </summary>
    std::string getLastStatusUpdate() const;
    void setLastStatusUpdate(std::string value);
    bool lastStatusUpdateIsSet() const;
    void unsetLastStatusUpdate();

protected:
    int64_t m_Id;
    bool m_IdIsSet;
    int64_t m_BackupDefId;
    bool m_BackupDefIdIsSet;
    std::string m_Status;
    bool m_StatusIsSet;
    std::string m_Started;
    bool m_StartedIsSet;
    std::string m_LastStatusUpdate;
    bool m_LastStatusUpdateIsSet;
};

}
}
}
}

#endif /* Backup_H_ */
