/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * BackupDef.h
 *
 * 
 */

#ifndef BackupDef_H_
#define BackupDef_H_


#include "ModelBase.h"

#include <string>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  BackupDef
    : public ModelBase
{
public:
    BackupDef();
    virtual ~BackupDef();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// BackupDef members

    /// <summary>
    /// 
    /// </summary>
    int64_t getId() const;
    void setId(int64_t value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string value);
    bool nameIsSet() const;
    void unsetName();
    /// <summary>
    /// 
    /// </summary>
    std::string getPath() const;
    void setPath(std::string value);
    bool pathIsSet() const;
    void unsetPath();
    /// <summary>
    /// 
    /// </summary>
    std::string getAdded() const;
    void setAdded(std::string value);
    bool addedIsSet() const;
    void unsetAdded();
    /// <summary>
    /// 
    /// </summary>
    std::string getHostName() const;
    void setHostName(std::string value);
    bool hostNameIsSet() const;
    void unsetHostName();

protected:
    int64_t m_Id;
    bool m_IdIsSet;
    std::string m_Name;
    bool m_NameIsSet;
    std::string m_Path;
    bool m_PathIsSet;
    std::string m_Added;
    bool m_AddedIsSet;
    std::string m_HostName;
    bool m_HostNameIsSet;
};

}
}
}
}

#endif /* BackupDef_H_ */
