/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * BackupDefs.h
 *
 * 
 */

#ifndef BackupDefs_H_
#define BackupDefs_H_


#include "ModelBase.h"

#include "BackupDef.h"
#include <vector>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  BackupDefs
    : public ModelBase
{
public:
    BackupDefs();
    virtual ~BackupDefs();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// BackupDefs members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<BackupDef>>& getBackupdefs();
    bool backupdefsIsSet() const;
    void unsetBackupdefs();

protected:
    std::vector<std::shared_ptr<BackupDef>> m_Backupdefs;
    bool m_BackupdefsIsSet;
};

}
}
}
}

#endif /* BackupDefs_H_ */
