/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * BackupInfo.h
 *
 * 
 */

#ifndef BackupInfo_H_
#define BackupInfo_H_


#include "ModelBase.h"

#include "File.h"
#include <vector>
#include "FullBackupDefInfo.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  BackupInfo
    : public ModelBase
{
public:
    BackupInfo();
    virtual ~BackupInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// BackupInfo members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<FullBackupDefInfo> getInfo() const;
    void setInfo(std::shared_ptr<FullBackupDefInfo> value);
    bool infoIsSet() const;
    void unsetInfo();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<File>>& getFiles();
    bool filesIsSet() const;
    void unsetFiles();

protected:
    std::shared_ptr<FullBackupDefInfo> m_Info;
    bool m_InfoIsSet;
    std::vector<std::shared_ptr<File>> m_Files;
    bool m_FilesIsSet;
};

}
}
}
}

#endif /* BackupInfo_H_ */
