/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * CloseInformation.h
 *
 * 
 */

#ifndef CloseInformation_H_
#define CloseInformation_H_


#include "ModelBase.h"

#include "Object.h"
#include <map>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  CloseInformation
    : public ModelBase
{
public:
    CloseInformation();
    virtual ~CloseInformation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// CloseInformation members


protected:
};

}
}
}
}

#endif /* CloseInformation_H_ */
