/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * Configuration.h
 *
 * 
 */

#ifndef Configuration_H_
#define Configuration_H_


#include "ModelBase.h"

#include "Object.h"
#include <vector>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Configuration
    : public ModelBase
{
public:
    Configuration();
    virtual ~Configuration();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Configuration members


protected:
};

}
}
}
}

#endif /* Configuration_H_ */
