/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "ConfigurationBody.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

ConfigurationBody::ConfigurationBody()
{
    m_ConfigIsSet = false;
    
}

ConfigurationBody::~ConfigurationBody()
{
}

void ConfigurationBody::validate()
{
    // TODO: implement validation
}

nlohmann::json ConfigurationBody::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_ConfigIsSet)
    {
        val["config"] = ModelBase::toJson(m_Config);
    }
    

    return val;
}

void ConfigurationBody::fromJson(nlohmann::json& val)
{
    if(val.find("config") != val.end())
    {
        if(!val["config"].is_null())
        {
            std::shared_ptr<Configuration> newItem(new Configuration());
            newItem->fromJson(val["config"]);
            setConfig( newItem );
        }
        
    }
    
}


std::shared_ptr<Configuration> ConfigurationBody::getConfig() const
{
    return m_Config;
}
void ConfigurationBody::setConfig(std::shared_ptr<Configuration> value)
{
    m_Config = value;
    m_ConfigIsSet = true;
}
bool ConfigurationBody::configIsSet() const
{
    return m_ConfigIsSet;
}
void ConfigurationBody::unsetConfig()
{
    m_ConfigIsSet = false;
}

}
}
}
}

