/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * ConfigurationBody.h
 *
 * 
 */

#ifndef ConfigurationBody_H_
#define ConfigurationBody_H_


#include "ModelBase.h"

#include "Configuration.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ConfigurationBody
    : public ModelBase
{
public:
    ConfigurationBody();
    virtual ~ConfigurationBody();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// ConfigurationBody members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Configuration> getConfig() const;
    void setConfig(std::shared_ptr<Configuration> value);
    bool configIsSet() const;
    void unsetConfig();

protected:
    std::shared_ptr<Configuration> m_Config;
    bool m_ConfigIsSet;
};

}
}
}
}

#endif /* ConfigurationBody_H_ */
