/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "CreateBackupDef.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

CreateBackupDef::CreateBackupDef()
{
    m_Name = "";
    m_NameIsSet = false;
    m_Path = "";
    m_PathIsSet = false;
    m_ConfigIsSet = false;
    
}

CreateBackupDef::~CreateBackupDef()
{
}

void CreateBackupDef::validate()
{
    // TODO: implement validation
}

nlohmann::json CreateBackupDef::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_NameIsSet)
    {
        val["name"] = ModelBase::toJson(m_Name);
    }
    if(m_PathIsSet)
    {
        val["path"] = ModelBase::toJson(m_Path);
    }
    if(m_ConfigIsSet)
    {
        val["config"] = ModelBase::toJson(m_Config);
    }
    

    return val;
}

void CreateBackupDef::fromJson(nlohmann::json& val)
{
    if(val.find("name") != val.end())
    {
        setName(val.at("name"));
        
    }
    if(val.find("path") != val.end())
    {
        setPath(val.at("path"));
        
    }
    if(val.find("config") != val.end())
    {
        if(!val["config"].is_null())
        {
            std::shared_ptr<Configuration> newItem(new Configuration());
            newItem->fromJson(val["config"]);
            setConfig( newItem );
        }
        
    }
    
}


std::string CreateBackupDef::getName() const
{
    return m_Name;
}
void CreateBackupDef::setName(std::string value)
{
    m_Name = value;
    m_NameIsSet = true;
}
bool CreateBackupDef::nameIsSet() const
{
    return m_NameIsSet;
}
void CreateBackupDef::unsetName()
{
    m_NameIsSet = false;
}
std::string CreateBackupDef::getPath() const
{
    return m_Path;
}
void CreateBackupDef::setPath(std::string value)
{
    m_Path = value;
    m_PathIsSet = true;
}
bool CreateBackupDef::pathIsSet() const
{
    return m_PathIsSet;
}
void CreateBackupDef::unsetPath()
{
    m_PathIsSet = false;
}
std::shared_ptr<Configuration> CreateBackupDef::getConfig() const
{
    return m_Config;
}
void CreateBackupDef::setConfig(std::shared_ptr<Configuration> value)
{
    m_Config = value;
    m_ConfigIsSet = true;
}
bool CreateBackupDef::configIsSet() const
{
    return m_ConfigIsSet;
}
void CreateBackupDef::unsetConfig()
{
    m_ConfigIsSet = false;
}

}
}
}
}

