/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * ErrorInformation.h
 *
 * 
 */

#ifndef ErrorInformation_H_
#define ErrorInformation_H_


#include "ModelBase.h"

#include "Object.h"
#include <map>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ErrorInformation
    : public ModelBase
{
public:
    ErrorInformation();
    virtual ~ErrorInformation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// ErrorInformation members


protected:
};

}
}
}
}

#endif /* ErrorInformation_H_ */
