/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * FullBackupDefInfo.h
 *
 * 
 */

#ifndef FullBackupDefInfo_H_
#define FullBackupDefInfo_H_


#include "ModelBase.h"

#include "BackupDef.h"
#include "Backup.h"
#include <vector>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  FullBackupDefInfo
    : public ModelBase
{
public:
    FullBackupDefInfo();
    virtual ~FullBackupDefInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// FullBackupDefInfo members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<BackupDef> getDef() const;
    void setDef(std::shared_ptr<BackupDef> value);
    bool defIsSet() const;
    void unsetDef();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Backup>>& getBackups();
    bool backupsIsSet() const;
    void unsetBackups();

protected:
    std::shared_ptr<BackupDef> m_Def;
    bool m_DefIsSet;
    std::vector<std::shared_ptr<Backup>> m_Backups;
    bool m_BackupsIsSet;
};

}
}
}
}

#endif /* FullBackupDefInfo_H_ */
