/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "HelpInformation.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

HelpInformation::HelpInformation()
{
    
}

HelpInformation::~HelpInformation()
{
}

void HelpInformation::validate()
{
    // TODO: implement validation
}

nlohmann::json HelpInformation::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void HelpInformation::fromJson(nlohmann::json& val)
{
    
}



}
}
}
}

