/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "ProgramInformation.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

ProgramInformation::ProgramInformation()
{
    m_Version = "";
    m_VersionIsSet = false;
    m_Hostname = "";
    m_HostnameIsSet = false;
    
}

ProgramInformation::~ProgramInformation()
{
}

void ProgramInformation::validate()
{
    // TODO: implement validation
}

nlohmann::json ProgramInformation::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_VersionIsSet)
    {
        val["version"] = ModelBase::toJson(m_Version);
    }
    if(m_HostnameIsSet)
    {
        val["hostname"] = ModelBase::toJson(m_Hostname);
    }
    

    return val;
}

void ProgramInformation::fromJson(nlohmann::json& val)
{
    if(val.find("version") != val.end())
    {
        setVersion(val.at("version"));
        
    }
    if(val.find("hostname") != val.end())
    {
        setHostname(val.at("hostname"));
        
    }
    
}


std::string ProgramInformation::getVersion() const
{
    return m_Version;
}
void ProgramInformation::setVersion(std::string value)
{
    m_Version = value;
    m_VersionIsSet = true;
}
bool ProgramInformation::versionIsSet() const
{
    return m_VersionIsSet;
}
void ProgramInformation::unsetVersion()
{
    m_VersionIsSet = false;
}
std::string ProgramInformation::getHostname() const
{
    return m_Hostname;
}
void ProgramInformation::setHostname(std::string value)
{
    m_Hostname = value;
    m_HostnameIsSet = true;
}
bool ProgramInformation::hostnameIsSet() const
{
    return m_HostnameIsSet;
}
void ProgramInformation::unsetHostname()
{
    m_HostnameIsSet = false;
}

}
}
}
}

