/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * ProgramInformation.h
 *
 * 
 */

#ifndef ProgramInformation_H_
#define ProgramInformation_H_


#include "ModelBase.h"

#include <string>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ProgramInformation
    : public ModelBase
{
public:
    ProgramInformation();
    virtual ~ProgramInformation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// ProgramInformation members

    /// <summary>
    /// 
    /// </summary>
    std::string getVersion() const;
    void setVersion(std::string value);
    bool versionIsSet() const;
    void unsetVersion();
    /// <summary>
    /// 
    /// </summary>
    std::string getHostname() const;
    void setHostname(std::string value);
    bool hostnameIsSet() const;
    void unsetHostname();

protected:
    std::string m_Version;
    bool m_VersionIsSet;
    std::string m_Hostname;
    bool m_HostnameIsSet;
};

}
}
}
}

#endif /* ProgramInformation_H_ */
