/**
* Smart Backup Utility
* HTTP Server for Smart Backup Utility
*
* OpenAPI spec version: 1.0.0
* Contact: Shai@Roitman.info
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "RestoreOptions.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

RestoreOptions::RestoreOptions()
{
    m_Id = 0L;
    m_IdIsSet = false;
    m_date = "";
    m_dateIsSet = false;
    
}

RestoreOptions::~RestoreOptions()
{
}

void RestoreOptions::validate()
{
    // TODO: implement validation
}

nlohmann::json RestoreOptions::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_IdIsSet)
    {
        val["id"] = m_Id;
    }
    if(m_dateIsSet)
    {
        val["date"] = ModelBase::toJson(m_date);
    }
    

    return val;
}

void RestoreOptions::fromJson(nlohmann::json& val)
{
    if(val.find("id") != val.end())
    {
        setId(val.at("id"));
    }
    if(val.find("date") != val.end())
    {
        setDate(val.at("date"));
        
    }
    
}


int64_t RestoreOptions::getId() const
{
    return m_Id;
}
void RestoreOptions::setId(int64_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool RestoreOptions::idIsSet() const
{
    return m_IdIsSet;
}
void RestoreOptions::unsetId()
{
    m_IdIsSet = false;
}
std::string RestoreOptions::getDate() const
{
    return m_date;
}
void RestoreOptions::setDate(std::string value)
{
    m_date = value;
    m_dateIsSet = true;
}
bool RestoreOptions::dateIsSet() const
{
    return m_dateIsSet;
}
void RestoreOptions::unsetdate()
{
    m_dateIsSet = false;
}

}
}
}
}

