swagger: '2.0'
info:
  description: HTTP Server for Smart Backup Utility
  version: 1.0.0
  title: Smart Backup Utility
  contact:
    email: Shai@Roitman.info
host: sbu.swagger.io
basePath: /
schemes:
  - http
paths:
  /info:
    get:
      summary: Return the information of the system
      produces: 
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ProgramInformation'
  /backupDef:
    get:
      summary: Retrieves currently defined backup definitions objects
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items: 
              $ref: '#/definitions/BackupDef'
    post:
      summary: Create a new backup def
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: BackupDef object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/CreateBackupDef'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/BackupDef'
        '405':
          description: Invalid input
  /backupDef/{id}:
    get:
      summary: Retrieve the backupDef
      parameters: 
        - in: path
          name: id
          type: string
          required: true
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FullBackupDefInfo'
  /backupDef/{id}/backup:
    post:
      summary: Create a new backup
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Backup'
        '405':
          description: Invalid input
  /backupDef/{id}/backup/{bid}:
    get:
      summary: Retrieve backup information
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: path
          name: bid
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/BackupInfo'
        '405':
          description: Invalid input
  /backupDef/{id}/restore:
    post:
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: body
          name: body
          description: Restore Backup
          required: true
          schema:
            $ref: '#/definitions/RestoreOptions'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Backup'
        '405':
          description: Invalid input
definitions:
  ProgramInformation:
    type: object
    properties:
      version:
        type: string
      hostname:
        type: string
  CreateBackupDef:
    type: object
    properties:
      name:
        type: string
      path:
        type: string
  BackupDef:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      path:
        type: string
        format: path
      added:
        type: string
        format: date-time
      hostName:
        type: string
  Backup:
    type: object
    properties:
      id:
        type: integer
        format: int64
      backupDefId:
        type: integer
        format: int64
      status:
          type: string
      started:
        type: string
        format: date-time
      lastStatusUpdate:
        type: string
        format: date-time
  FullBackupDefInfo:
    type: object
    properties:
      def:
        $ref: '#/definitions/BackupDef'
      backups:
        type: array
        items: 
          $ref: '#/definitions/Backup'
  BackupInfo:
    type: object
    properties:
      info:
        $ref: '#/definitions/FullBackupDefInfo'
      files:
        type: array
        items:
          $ref: '#/definitions/File'
  File:
    type: object
    properties:
      id:
        type: integer
        format: int64
      status:
        type: string
      type:
        type: string
      path:
        type: string
        format: path
      size:
        type: integer
        format: int64
      created:
        type: string
        format: date-time
      modified:
        type: string
        format: date-time
      accessed:
        type: string
        format: date-time
      digestType:
        type: string
      digestValue:
        type: string
      fileHandle:
        type: string
  RestoreOptions:
    type: object
    properties:
      id:
        type: integer
        format: int64
      date:
        type: string
        format: date-time

